config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies",          to: "pages#cookies", as: "cookies"
  get "toolkit",          to: "toolkit#index"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'rezervacija/:token',               to: 'space_bookings#show', as: :space_booking
  resources :posts,                       only: [:index, :show], path: :novosti
  resources :documents,                   only: :index, path: :dokumenti
  resources :faqs,                        only: :index, path: 'cesto-postavljana-pitanja'
  resources :legal_pages,                 only: :show, path: 'pravne-stranice'

  resources :spaces, path: :prostori do
    member do

      scope :rezervacija do
        get 'opcenito',                   to: 'space_bookings#general', as: :booking_general
        post 'opcenito',                  to: 'space_bookings#save_general', as: :booking_save_general
        get 'dohvati-termine',            to: 'space_bookings#get_terms', as: :get_date_terms
        get 'datumi',                     to: 'space_bookings#dates', as: :booking_dates
        post 'datumi',                    to: 'space_bookings#save_dates', as: :booking_save_dates
        post 'dodaj-termin',              to: 'space_bookings#add_term', as: :add_term
        delete 'ukloni-termin/:term_id',  to: 'space_bookings#destroy_term', as: :destroy_term
      end

      scope :najam do
        get 'zahtjev',                    to: 'space_rent_requests#new', as: :new_space_rent_request
        post 'zahtjev',                   to: 'space_rent_requests#create', as: :space_rent_requests
      end

    end
  end

  namespace :admin do
    root "admins#index"
    get "toolkit", to: "toolkit#index"
    resources :admins,                      path: :administratori
    resource :admin_account,                only: [:show, :update], path: :racun
    resources :spaces,                      path: :prostori
    resources :space_bookings,              path: :rezervacije do
      member do
        patch 'posalji-notifikaciju', to: 'space_bookings#send_update_email', as: :send_notification
      end
    end
    resources :space_rent_requests,         only: [:index, :show], path: :zahtjevi
    resources :space_booking_terms,         only: :none, path: 'termini' do
      member do
        patch 'status/:status', to: 'space_booking_terms#change_status'
      end
    end
    resources :posts,                       path: :novosti
    get 'neobjavljene-novosti',             to: 'posts#index', defaults: { filter: :unpublished }, as: :unpublished_posts
    resources :page_meta_tags,              only: [:index, :show, :update], path: 'meta-oznake-stranica'
    resources :documents,                   only: [:index, :show, :new, :create, :update, :destroy], path: :dokumenti do
      collection do
        patch :sort
      end
    end
    resources :faqs,                        only: [:index, :show, :new, :create, :update, :destroy], path: :pitanja do
      collection do
        patch :sort
      end
    end
    resources :legal_pages,                 only: [:index, :new, :create, :show, :update, :destroy], path: 'pravne-stranice' do
      collection do
        patch :sort
      end
    end
    resource :app_setting,                  only: [:show, :update], settings: /tekst-pristanka/, path: 'postavke/:settings'
    resource :landing_page,                 only: [:show, :update], path: 'pocetna-stranica'
  end

end

app/models/page_meta_tag.rb
class PageMetaTag < ApplicationRecord
	mount_uploader :image, ImageUploader

	validates_uniqueness_of :page
	validates_presence_of :title, :description, :keywords
	validates_length_of :title, maximum: 20
	validates_length_of :description, maximum: 150

	def resolve_og_title
		og_title.blank? ? title : og_title
	end
end

app/controllers/admin/page_meta_tags_controller.rb
class Admin::PageMetaTagsController < Admin::BaseController
	before_action :set_page_meta_tag, only: [:show, :update]

	def index
		@page_meta_tags = PageMetaTag.order(:created_at)
	end

	def show; end

	def update
		if @page_meta_tag.update(page_meta_tag_params)
			redirect_to [:admin, @page_meta_tag], notice: t('message.updated')
		else
			render :show
		end
	end

	private

	def set_page_meta_tag
		@page_meta_tag = PageMetaTag.find(params[:id])
	end

	def page_meta_tag_params
		params.require(:page_meta_tag).permit(:title, :og_title, :description, :keywords, :image, :image_cache)
	end
end

app/views/admin/page_meta_tags/_form.html.erb
<%= form_for [:admin, @page_meta_tag], html: {class: 'form grid'} do |f| %>

  <div class="form__field">
    <%= f.label :title, class: "label" %>
    <em><%= t('page_meta_tag.title_desc') %></em>
    <%= f.text_field :title, class: "input js_validate_len-max(20)" %>
  </div>

  <div class="form__field">
    <%= f.label :og_title, class: "label" %>
    <%= f.text_field :og_title, class: "input" %>
  </div>

  <div class="field input__field--text">
    <%= f.label :image, class: "label" %>
    <div class="image_field seo_image">
      <img src="<%= f.object.image_url %>" class= "img_prev" alt='Drop File here or click to upload'>
       <p class="text--center"><%= t('image_upload') %></p>
      <%= f.file_field :image, class: "image_file_field" %>
      <%= f.hidden_field :image_cache %>
    </div>
  </div>

  <div class="form__field">
    <%= f.label :description, class: "label" %>
    <%= f.text_area :description, class: "input js_validate_len-max(150)" %>
  </div>

  <div class="form__field">
    <%= f.label :keywords, class: "label" %>
    <em><%= t('seo_keywords_recommendation') %></em>
    <%= f.text_area :keywords, class: "input js_validate_len-max(150)" %>
  </div>

  <div class="actions">
    <%= f.submit t('save'), class: "btn btn--primary sticky-submit", data: { disable_with: t('please_wait') } %>
  </div>
<% end %>

app/views/admin/page_meta_tags/index.html.erb
<header class="header header--double">
  <h1><%= t('admin_nav.page_meta_tags') %></h1>
</header>

<section class="section section--6 section--double users">
	<table class="clear-admin-agent-styles table datatable table__icon--4">
		<thead>
			<tr class="table__head--wrap">
		    <th class="table__head col col--1"><%= tf('page_meta_tag.title') %></th>
		    <th class="table__head col col--1"><%= t('actions') %></th>
		  </tr>
		</thead>

		<tbody>
			<% @page_meta_tags.each do |page_meta_tag| %>
	  		<tr class="table__item--wrap">
		      <td class="table__item col col--2 account--activity">
				<%= page_meta_tag.title %>
		      </td>
		      <td class="table__item table__icon--wrap col col--1">	
					<%= link_to admin_page_meta_tag_path(page_meta_tag), class: "table__icon" do %>
						<%= inline_svg "icons/eye-ban-18.svg" %>
					<% end %>
		      </td>
			</tr>
		  <% end %>
		</tbody>
	</table>
</section>

<script>
	init_datatable({lang: "<%= I18n.locale %>"});
</script>

app/views/admin/page_meta_tags/show.html.erb
<header class="header header--small">
	<%= link_to admin_page_meta_tags_path, class: "btn btn--back" do %>
		<div class="arrow--left"></div>
	<% end %>

	<div class="header__content">
		<h1><%= t('admin_nav.page_meta_tags') %></h1>
		<p><%= t('editing') %></p>
	</div>
</header>

<section class="section section--12 section--padded">
	<%= render 'form' %>
</section>