config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies",          to: "pages#cookies", as: "cookies"
  get "toolkit",          to: "toolkit#index"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'rezervacija/:token',               to: 'space_bookings#show', as: :space_booking
  resources :posts,                       only: [:index, :show], path: :novosti
  resources :documents,                   only: :index, path: :dokumenti
  resources :faqs,                        only: :index, path: 'cesto-postavljana-pitanja'
  resources :legal_pages,                 only: :show, path: 'pravne-stranice'

  resources :spaces, path: :prostori do
    member do

      scope :rezervacija do
        get 'opcenito',                   to: 'space_bookings#general', as: :booking_general
        post 'opcenito',                  to: 'space_bookings#save_general', as: :booking_save_general
        get 'dohvati-termine',            to: 'space_bookings#get_terms', as: :get_date_terms
        get 'datumi',                     to: 'space_bookings#dates', as: :booking_dates
        post 'datumi',                    to: 'space_bookings#save_dates', as: :booking_save_dates
        post 'dodaj-termin',              to: 'space_bookings#add_term', as: :add_term
        delete 'ukloni-termin/:term_id',  to: 'space_bookings#destroy_term', as: :destroy_term
      end

      scope :najam do
        get 'zahtjev',                    to: 'space_rent_requests#new', as: :new_space_rent_request
        post 'zahtjev',                   to: 'space_rent_requests#create', as: :space_rent_requests
      end

    end
  end

  namespace :admin do
    root "admins#index"
    get "toolkit", to: "toolkit#index"
    resources :admins,                      path: :administratori
    resource :admin_account,                only: [:show, :update], path: :racun
    resources :spaces,                      path: :prostori
    resources :space_bookings,              path: :rezervacije do
      member do
        patch 'posalji-notifikaciju', to: 'space_bookings#send_update_email', as: :send_notification
      end
    end
    resources :space_rent_requests,         only: [:index, :show], path: :zahtjevi
    resources :space_booking_terms,         only: :none, path: 'termini' do
      member do
        patch 'status/:status', to: 'space_booking_terms#change_status'
      end
    end
    resources :posts,                       path: :novosti
    get 'neobjavljene-novosti',             to: 'posts#index', defaults: { filter: :unpublished }, as: :unpublished_posts
    resources :page_meta_tags,              only: [:index, :show, :update], path: 'meta-oznake-stranica'
    resources :documents,                   only: [:index, :show, :new, :create, :update, :destroy], path: :dokumenti do
      collection do
        patch :sort
      end
    end
    resources :faqs,                        only: [:index, :show, :new, :create, :update, :destroy], path: :pitanja do
      collection do
        patch :sort
      end
    end
    resources :legal_pages,                 only: [:index, :new, :create, :show, :update, :destroy], path: 'pravne-stranice' do
      collection do
        patch :sort
      end
    end
    resource :app_setting,                  only: [:show, :update], settings: /tekst-pristanka/, path: 'postavke/:settings'
    resource :landing_page,                 only: [:show, :update], path: 'pocetna-stranica'
  end

end

app/views/layouts/admin/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert-error">
        <h2><%= "Broj grešaka: #{object.errors.count}" %></h2>
      </div>
      <div class="alert-error-list">
        <% object.errors.full_messages.each do |msg| %>
            <p>* <%= msg %></p>
        <% end %>
      </div>
    </div>
<% end %>

<script>
  $(function(){
    $('#error_explanation').delay(1000).animate({backgroundColor: '#FFFFFF', color: "#c62828"}, 1000);
  });
</script>

app/views/layouts/admin/_footer.html.erb
<footer class="footer">

  <div class="layout--padded">
    <p>Bamboo CMS footer</p>
  </div>

</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navigation">
  <%= link_to "Bamboo Lab", "http://bamboolab.eu", class: "logo--bamboo", target: "_blank" %>

  <div class="navigation__content">
    <div class="navigation__account">
      <%= link_to admin_admin_path(current_admin), class: "account__link" do %>
        <%= image_tag current_admin.image_url(:thumb), class: "account__img" %>
      <% end %>
      <%= inline_svg "icons/shape-arrow-down.svg", class: "account__arrow" %>
    </div>

      <div class="dropdown">
        <%= link_to t('admin_nav.account_options'), admin_admin_account_path, class: "dropdown__link" %>
        <%= link_to t("admin_nav.log_out"), destroy_admin_session_path, data: {method: :delete}, class: "dropdown__link" %>
      </div>
  </div>
</nav>

<div class="js_notifications"><%= render 'layouts/admin/notifications' %></div>

<script>
  $('.account__arrow').on('click', function(){
    $(this).toggleClass('active');
    $(".dropdown").animate({height: 'toggle'});
  });

  $(".dropdown").click(function(e){
    e.stopPropagation();
  });

   $(".account__arrow").click(function(e){
    e.stopPropagation();
  });

  $(document).click(function(){
    if($(".account__arrow").hasClass("active")) {
      $(".dropdown").animate({height: 'toggle'});
      $(".account__arrow").removeClass("active");
    }
  });


</script>

app/views/layouts/admin/_navigation.html.erb
<div class="sidebar">
  <nav class="sidebar__content">
    <%= link_to admin_root_path, class: 'sidebar__logo', title: 'Stara Pekara' do %>
      <%= inline_svg 'logo.svg', class: 'logo-primary', title: 'Stara Pekara' %>
    <% end %>

    <% if current_admin.permitted?(:admins) %>
      <%= active_link_to admin_admins_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/users.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.accounts") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:admins) %>
      <%= active_link_to admin_page_meta_tags_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/programs.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.page_meta_tags") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:admins) %>
      <%= active_link_to admin_landing_page_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/house-icon.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.landing_page") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:admins) %>
      <%= active_link_to admin_spaces_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/offices.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.spaces") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_space_bookings_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/appointments.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.space_bookings") %>
        <%= nav_indicator(id: 'unread-bookings', unread: SpaceBooking.unread.count) %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_space_rent_requests_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/calendar-icon.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.space_rent_requests") %>
        <%= nav_indicator(id: 'unread-rent-requests', unread: SpaceRentRequest.unread.count) %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_posts_path, class: 'sidebar__link', active: [['admin/posts'], []], class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/news.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.posts") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_documents_path, class: 'sidebar__link', active: [['admin/documents'], []], class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/report.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.documents") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_faqs_path, class: 'sidebar__link', active: [['admin/faqs'], []], class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/services.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.faqs") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_legal_pages_path, class: 'sidebar__link', active: [['admin/legal_pages'], []], class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/law.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.legal_pages") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_app_setting_path(settings: 'tekst-pristanka'), class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/tool-1.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.app_settings") %>
      <% end %>
    <% end %>

    <% if current_admin.permitted?(:contact_messages) %>
      <%= active_link_to admin_toolkit_path, class: 'sidebar__link', active: :inclusive, class_active: 'active-link' do %>
        <%= inline_svg "icons/nav/tool-1.svg", class: 'sidebar__icon' %>
        <%= t("admin_nav.toolkit") %>
      <% end %>
    <% end %>

    <%= link_to root_path, class: 'sidebar__link' do %>
      <%= inline_svg "icons/nav/exit.svg", class: 'sidebar__icon' %>
      <%= t("admin_nav.go_to_web") %>
    <% end %>
  </nav>
</div>

<style>
    .js_messages_count{
        background: red;
        padding: 3px 5px;
        border-radius: 50px;
    }
</style>

app/views/layouts/admin/_notifications.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) and msg.length > 0 %>
  <div class="message">
    <div class="row">
      <div class="small-12 columns">

        <div class="close js_close_flash">
          <div data-alert class="alert-box <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :p, msg %>
          </div>
        </div>

      </div>
    </div>
  </div>
  <% end %>
<% end %>

<script>
  $("body").on("mousemove touchmove", function(){
    $(".alert-box").delay(3000);
    $(".alert-box").slideUp(500,function() { $(".alert-box").remove() });
    $(".js_close_flash").on("click", function() {
        $(".alert-box").slideUp(500,function() { $(".alert-box").remove() });
    });
  });
</script>

app/views/layouts/admin/dashboard.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="https://www.facebook.com/2008/fbml">

<head>
  <title><%= "Admin | #{AppInfo.name} CMS" %></title>

  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <%= stylesheet_link_tag 'admin', media: 'all' %>
  <%= javascript_include_tag 'admin' %>

  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>

<body>

   <div class="layout--main mobile-splash">
    <%= inline_svg "icons/x2_black.svg" %>
    <p class="text--center text--large strong"><%= t('mobile_dashboard_info') %></p>
    <br>
    <a href="javascript:history.back()" class="btn btn--primary"><%= t('back') %></a>
  </div>

  <div class="<%= 'grid grid--12' unless @navigation_disabled %> hidden--small">

    <%= render 'layouts/admin/navigation' unless @navigation_disabled %>

    <div class="<%= @navigation_disabled ? 'main layout--main' : 'main' %>">
      <%= render 'layouts/admin/header' unless @header_disabled %>

      <div class="grid grid--12 <%= 'main__content' unless @navigation_disabled %>">
        <%= yield %>
      </div>

      <%#= render 'layouts/admin/footer' unless @footer_disabled %>
    </div>

  </div>

  <div id="popup-message"></div>

  <%#= render 'layouts/modal' %>
</body>
</html>