config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies",          to: "pages#cookies", as: "cookies"
  get "toolkit",          to: "toolkit#index"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'rezervacija/:token',               to: 'space_bookings#show', as: :space_booking
  resources :posts,                       only: [:index, :show], path: :novosti
  resources :documents,                   only: :index, path: :dokumenti
  resources :faqs,                        only: :index, path: 'cesto-postavljana-pitanja'
  resources :legal_pages,                 only: :show, path: 'pravne-stranice'

  resources :spaces, path: :prostori do
    member do

      scope :rezervacija do
        get 'opcenito',                   to: 'space_bookings#general', as: :booking_general
        post 'opcenito',                  to: 'space_bookings#save_general', as: :booking_save_general
        get 'dohvati-termine',            to: 'space_bookings#get_terms', as: :get_date_terms
        get 'datumi',                     to: 'space_bookings#dates', as: :booking_dates
        post 'datumi',                    to: 'space_bookings#save_dates', as: :booking_save_dates
        post 'dodaj-termin',              to: 'space_bookings#add_term', as: :add_term
        delete 'ukloni-termin/:term_id',  to: 'space_bookings#destroy_term', as: :destroy_term
      end

      scope :najam do
        get 'zahtjev',                    to: 'space_rent_requests#new', as: :new_space_rent_request
        post 'zahtjev',                   to: 'space_rent_requests#create', as: :space_rent_requests
      end

    end
  end

  namespace :admin do
    root "admins#index"
    get "toolkit", to: "toolkit#index"
    resources :admins,                      path: :administratori
    resource :admin_account,                only: [:show, :update], path: :racun
    resources :spaces,                      path: :prostori
    resources :space_bookings,              path: :rezervacije do
      member do
        patch 'posalji-notifikaciju', to: 'space_bookings#send_update_email', as: :send_notification
      end
    end
    resources :space_rent_requests,         only: [:index, :show], path: :zahtjevi
    resources :space_booking_terms,         only: :none, path: 'termini' do
      member do
        patch 'status/:status', to: 'space_booking_terms#change_status'
      end
    end
    resources :posts,                       path: :novosti
    get 'neobjavljene-novosti',             to: 'posts#index', defaults: { filter: :unpublished }, as: :unpublished_posts
    resources :page_meta_tags,              only: [:index, :show, :update], path: 'meta-oznake-stranica'
    resources :documents,                   only: [:index, :show, :new, :create, :update, :destroy], path: :dokumenti do
      collection do
        patch :sort
      end
    end
    resources :faqs,                        only: [:index, :show, :new, :create, :update, :destroy], path: :pitanja do
      collection do
        patch :sort
      end
    end
    resources :legal_pages,                 only: [:index, :new, :create, :show, :update, :destroy], path: 'pravne-stranice' do
      collection do
        patch :sort
      end
    end
    resource :app_setting,                  only: [:show, :update], settings: /tekst-pristanka/, path: 'postavke/:settings'
    resource :landing_page,                 only: [:show, :update], path: 'pocetna-stranica'
  end

end

app/models/space_rent_request.rb
class SpaceRentRequest < ApplicationRecord
  attr_accessor :consent

	before_create :set_token
  validates_uniqueness_of :token
  validates_presence_of :first_name, :last_name, :organisation, :phone, :email, :people_count, :work_plan, :work_goal
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP, allow_blank: true

  belongs_to :space

  default_scope { order(created_at: :desc) }
  scope :unread, ->{ where(seen_at: nil) }

  def full_name
    "#{first_name} #{last_name}"
  end

  def set_token
    self.token = generate_token
  end

  def generate_token
    token = SecureRandom.urlsafe_base64
    SpaceRentRequest.exists?(token: token) ? generate_token : token
  end
end

app/controllers/admin/space_rent_requests_controller.rb
class Admin::SpaceRentRequestsController < Admin::BaseController

	def index
		@space_rent_requests = SpaceRentRequest.all
	end

	def show
		@space_rent_request = SpaceRentRequest.find(params[:id])
		@space_rent_request.update_column(:seen_at, DateTime.current) unless @space_rent_request.seen_at
	end

end

app/controllers/space_rent_requests_controller.rb
class SpaceRentRequestsController < ApplicationController
	before_action :set_space

	def new
		@app_settings = AppSetting.first_or_create
		@space_rent_request = @space.space_rent_requests.new
	end

	def create
		@space_rent_request = @space.space_rent_requests.new(space_rent_request_params)
		if @space_rent_request.save
			redirect_to space_path(@space), notice: t('message.sent')
		else
			@app_settings = AppSetting.first_or_create
			render :new
		end
	end

	private

	def space_rent_request_params
		params.require(:space_rent_request).permit(
			:first_name, :last_name, :organisation, :phone, :email, :people_count,
			:consent, :work_plan, :work_goal, :partners, :other
		)
	end

	def set_space
		@space = Space.find(params[:id])
		raise ActiveRecord::RecordNotFound unless @space.rentable
	end
end

app/views/admin/space_rent_requests/index.html.erb
<header class="header header--double">
  <h1><%= t('admin_nav.space_rent_requests') %></h1>
</header>

<section class="section section--12 section--double users">
	<table class="clear-admin-agent-styles table datatable table__icon--4">
		<thead>
			<tr class="table__head--wrap">
		    <th class="table__head col col--1"><%= tf('space_rent_request.created_at') %></th>
		    <th class="table__head col col--1"><%= tf('space_rent_request.for_space') %></th>
		    <th class="table__head col col--1"><%= tf('space_rent_request.organisation') %></th>
		    <th class="table__head col col--1"><%= tf('space_rent_request.full_name') %></th>
		    <th class="table__head col col--1"><%= t('actions') %></th>
		  </tr>
		</thead>

		<tbody>
			<% @space_rent_requests.each do |space_rent_request| %>
	  		<tr class="table__item--wrap">
		      <td class="table__item col col--1" data-sort="<%= space_rent_request.created_at.strftime('%Y%m%d') %>">
				<%= timestamp(space_rent_request.created_at) %>
		      </td>
		      <td class="table__item col col--1">
		      	<%= link_to space_rent_request.space.name, admin_space_path(space_rent_request.space), class: 'link' %>
		      </td>
		      <td class="table__item col col--1">
		      	<%= space_rent_request.organisation %>
		      </td>
		      <td class="table__item col col--1">
						<%= space_rent_request.full_name %>
		      </td>
		      <td class="table__item table__icon--wrap col col--1">	
					<%= link_to admin_space_rent_request_path(space_rent_request), class: "table__icon" do %>
						<%= inline_svg "icons/eye-ban-18.svg" %>
					<% end %>
		      </td>
				</tr>
		  <% end %>
		</tbody>
	</table>
</section>

<script>
	init_datatable({lang: "<%= I18n.locale %>"});
</script>

app/views/admin/space_rent_requests/show.html.erb
<header class="header header--small">
	<%= link_to admin_space_rent_requests_path, class: "btn btn--back" do %>
		<div class="arrow--left"></div>
	<% end %>

	<div class="header__content">
		<h1><%= t('admin_nav.space_rent_requests') %></h1>
		<p><%= t('overview') %></p>
	</div>
</header>

<section class="section section--4 section--padded">
	<label class="label"><%= tf('space_rent_request.for_space') %></label>
	<p><%= link_to @space_rent_request.space.name, [:admin, @space_rent_request.space], class: 'link' %></p>
	<label class="label"><%= tf('space_rent_request.full_name') %></label>
	<p><%= @space_rent_request.full_name %></p>
	<label class="label"><%= tf('space_rent_request.organisation') %></label>
	<p><%= @space_rent_request.organisation %></p>
	<label class="label"><%= tf('space_rent_request.phone') %></label>
	<p><%= @space_rent_request.phone %></p>
	<label class="label"><%= tf('space_rent_request.email') %></label>
	<p><%= mail_to @space_rent_request.email, @space_rent_request.email, class: 'link' %></p>
	<label class="label"><%= tf('space_rent_request.people_count') %></label>
	<p><%= @space_rent_request.people_count %></p>
	<label class="label"><%= tf('space_rent_request.work_plan') %></label>
	<p><%= @space_rent_request.work_plan %></p>
	<label class="label"><%= tf('space_rent_request.work_goal') %></label>
	<p><%= @space_rent_request.work_goal %></p>
	<label class="label"><%= tf('space_rent_request.partners') %></label>
	<p><%= @space_rent_request.partners %></p>
	<label class="label"><%= tf('space_rent_request.other') %></label>
	<p><%= @space_rent_request.other %></p>
</section>