config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  root "pages#home"
  post "/tinymce_assets", to: "tinymce_assets#create"
  get "cookies",          to: "pages#cookies", as: "cookies"
  get "toolkit",          to: "toolkit#index"

  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'rezervacija/:token',               to: 'space_bookings#show', as: :space_booking
  resources :posts,                       only: [:index, :show], path: :novosti
  resources :documents,                   only: :index, path: :dokumenti
  resources :faqs,                        only: :index, path: 'cesto-postavljana-pitanja'
  resources :legal_pages,                 only: :show, path: 'pravne-stranice'

  resources :spaces, path: :prostori do
    member do

      scope :rezervacija do
        get 'opcenito',                   to: 'space_bookings#general', as: :booking_general
        post 'opcenito',                  to: 'space_bookings#save_general', as: :booking_save_general
        get 'dohvati-termine',            to: 'space_bookings#get_terms', as: :get_date_terms
        get 'datumi',                     to: 'space_bookings#dates', as: :booking_dates
        post 'datumi',                    to: 'space_bookings#save_dates', as: :booking_save_dates
        post 'dodaj-termin',              to: 'space_bookings#add_term', as: :add_term
        delete 'ukloni-termin/:term_id',  to: 'space_bookings#destroy_term', as: :destroy_term
      end

      scope :najam do
        get 'zahtjev',                    to: 'space_rent_requests#new', as: :new_space_rent_request
        post 'zahtjev',                   to: 'space_rent_requests#create', as: :space_rent_requests
      end

    end
  end

  namespace :admin do
    root "admins#index"
    get "toolkit", to: "toolkit#index"
    resources :admins,                      path: :administratori
    resource :admin_account,                only: [:show, :update], path: :racun
    resources :spaces,                      path: :prostori
    resources :space_bookings,              path: :rezervacije do
      member do
        patch 'posalji-notifikaciju', to: 'space_bookings#send_update_email', as: :send_notification
      end
    end
    resources :space_rent_requests,         only: [:index, :show], path: :zahtjevi
    resources :space_booking_terms,         only: :none, path: 'termini' do
      member do
        patch 'status/:status', to: 'space_booking_terms#change_status'
      end
    end
    resources :posts,                       path: :novosti
    get 'neobjavljene-novosti',             to: 'posts#index', defaults: { filter: :unpublished }, as: :unpublished_posts
    resources :page_meta_tags,              only: [:index, :show, :update], path: 'meta-oznake-stranica'
    resources :documents,                   only: [:index, :show, :new, :create, :update, :destroy], path: :dokumenti do
      collection do
        patch :sort
      end
    end
    resources :faqs,                        only: [:index, :show, :new, :create, :update, :destroy], path: :pitanja do
      collection do
        patch :sort
      end
    end
    resources :legal_pages,                 only: [:index, :new, :create, :show, :update, :destroy], path: 'pravne-stranice' do
      collection do
        patch :sort
      end
    end
    resource :app_setting,                  only: [:show, :update], settings: /tekst-pristanka/, path: 'postavke/:settings'
    resource :landing_page,                 only: [:show, :update], path: 'pocetna-stranica'
  end

end

app/views/admin/admins/_form.html.erb
<%= form_for [:admin, @admin], :html => {role: 'form', class: 'form'} do |f| %>

  <div class="grid grid--12">

    <div class="section__wrap--4">
      <section class="section section--padded">

        <%= f.submit t('save'), class: 'btn btn--primary btn--medium btn--save', data: {disable_with: 'Molim pričekajte...'} %>

        <fieldset class="form__fieldset">
          <%= render partial: 'layouts/admin/error_messages', as: :object, object: @admin %>
        </fieldset>

        <fieldset class="form__fieldset">

          <% if @admin.persisted? and @admin == current_admin %>

            <h2><%= f.label "Slika" %></h2>
            <div class="image-field">
              <%= image_tag f.object.image_url(:thumb), id: "img_prev", alt: "Click \"Browse\" to add an image" %>
            </div>

            <div class="field" >
              <%= f.file_field :image, :onchange => "readURL(this);" %>
            </div>

          <% end %>

          <div class="form__field input__field--text">
            <%= f.label :first_name, class: 'label' %>
            <%= f.text_field :first_name, class: "input" %>
          </div>

          <div class="form__field input__field--text">
            <%= f.label :last_name, class: 'label' %>
            <%= f.text_field :last_name, class: "input" %>
          </div>

          <div class="form__field input__field--text">
            <%= f.label "#{:email}*", class: 'label' %>
            <%= f.text_field :email, class: "input" %>
          </div>

        </fieldset>

        <% if @admin.persisted? and @admin == current_admin %>

          <fieldset class="form__fieldset">
            <div class="form__field input__field--text">
              <%= f.label :password, class: 'label' %>
              <%= f.password_field :password, class: "input" %>
            </div>

            <div class="form__field input__field--text">
              <%= f.label :password_confirmation, class: 'label' %>
              <%= f.password_field :password_confirmation, class: "input" %>
            </div>

          </fieldset>

        <% end %>

      </section>
    </div>

    <div class="section__wrap--8">
      <section class="section section--padded">

        <% if current_admin.superadmin && !@admin.superadmin %>
          <div class="form__field input__field--checkbox">
            <div class="checkbox--admin">
              <%= f.check_box :admin, class: "", id: "admin_checkbox" %>
              <%= f.label :admin, t("resource_permissions.admins"), class: 'input__label', for: 'admin_checkbox' %>
              <%= f.label :admin, t("resource_permissions.description.admins"), class: 'input__label--secondary' %>
            </div>
          </div>
        <% end %>


        <% unless current_admin == @admin %>
          <div id="permission_list">
            <p class="users__notification"><%= t('resource_permissions.dependency_explanation') %></p>

            <%= f.fields_for :resource_permissions do |ff| %>
              <div class="form__field">
                <%= ff.hidden_field :resource, class: "input" %>
              </div>

              <div class="form__field input__field--checkbox">
                <div class="checkbox">
                  <%= ff.check_box :permitted, class: "" %>
                  <%= ff.label :permitted, t("resource_permissions.#{ff.object.resource}"), class: 'input__label' %>
                  <%= ff.label :permitted, t("resource_permissions.description.#{ff.object.resource}"), class: 'input__label--secondary' %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      </section>
    </div>

  </div>

<% end %>

<script>
  $(function(){
      togglePermissionList();
    });

    $("#admin_checkbox").change(function() {
        togglePermissionList();
      });

    function togglePermissionList(){
        if ($("#admin_checkbox").is(":checked")){
            $("#permission_list").slideUp();
          }else{
              $("#permission_list").slideDown();
            }
      }
</script>

app/views/admin/admins/_permissions_info.html.erb
<ul class="users__premissions">
	<% admin.resource_permissions.map(&:resource).each do |resource| %>
		<li title="<%= t("resource_permissions.description.#{resource}") %>"><%= t("resource_permissions.#{resource}") if admin.permitted?(resource) %></li>
	<% end %>
</ul>

app/views/admin/admins/edit.html.erb
<header class="header header--small">
  <%= link_to admin_admins_path, class: "btn btn--back" do %>
    <div class="arrow--left"></div>
  <% end %>

  <div class="header__content">
    <h1><%= t('admin_nav.accounts') %></h1>
    <p><%= t('editing') %></p>
  </div>
</header>

<section class="section--12 users">
  <%= render 'form' %>
</section>

app/views/admin/admins/index.html.erb
<header class="header header--double">
  <h1><%= t('admin_nav.accounts') %></h1>

  <%= link_to t('admin.new_record'), new_admin_admin_path, class: "btn btn--primary btn--large" %>
</header>

<section class="section section--12 section--double users">
	<table class="clear-admin-agent-styles table datatable table__icon--4">
		<thead>
			<tr class="table__head--wrap">
		    <th class="table__head col col--2"><%= t('admin.email') %></th>
		    <th class="table__head col col--1"><%= t('admin.role') %></th>
		    <th class="table__head col col--1"><%= t('admin.number_of_logins') %></th>
		    <th class="table__head col col--1"><%= t('admin.number_of_logs') %></th>
		    <th class="table__head col col--1"><%= t('actions') %></th>
		  </tr>
		</thead>
		
		<tbody>
			<% @admins.each do |admin| %>
	  		<tr class="table__item--wrap">
		      <td class="table__item col col--2 account--activity">
			      <%= image_tag admin.image_url(:thumb), class: "activity__img" %>
			      <%= admin.full_name %>
		      </td>
		      <td class="table__item col col--1 js_admin_body" style="<%= "cursor: pointer;" if admin.moderator? %>">
		      	<span class="js_admin_role"><%= admins_role(admin) %></span>
		      	<div class="js_admin_permissions users__premissions--wrap" style="display: none;">
		      		<%= render 'admin/admins/permissions_info', admin: admin if admin.moderator? %>
	     			</div>
		      </td>
		      <td class="table__item col col--1"><%= admin.sign_in_count %></td>
		      <td class="table__item col col--1"><%#= admin.action_logs.size %></td>
		      <td class="table__item table__icon--wrap col col--1">	
					<%= link_to admin_admin_path(admin), class: "table__icon",  "data-tooltip" => t('show') do %>
						<%= inline_svg "icons/eye-ban-18.svg" %>
					<% end %>

					<% if permission_to_edit(admin) %>
						<%= link_to edit_admin_admin_path(admin), class: "table__icon",  "data-tooltip" => t('edit') do %>
							<%= inline_svg "icons/pen-group-3.svg" %>
						<% end %>
					<% end %>

			    	<% if permission_to_delete(admin) %>
						<%= link_to admin_admin_path(admin), method: :delete, data: {confirm: t('delete_confirm')}, class: "table__icon", "data-tooltip" => t('delete') do %>
							<%= inline_svg "icons/trash-simple.svg" %>
						<% end %>
					<% end %>

					<div class="users__arrow--wrap">
						<%= inline_svg "icons/shape-arrow-down.svg", class: "users__arrow js_admin_btn" if admin.moderator? %>
					</div>
		      </td>
				</tr>
		  <% end %>
		</tbody>
	</table>
</section>

<script>
	$('.js_admin_btn').click(function(){
		$(this).parents(".table__item").siblings(".js_admin_body").children(".js_admin_permissions").slideToggle();
		$(this).toggleClass("active");
	});
	$('.js_admin_body').click(function(){
		$(this).children(".js_admin_permissions").slideToggle();
		$(this).parents(".table__item--wrap").find(".js_admin_btn").toggleClass("active");
	});
init_datatable({lang: "<%= I18n.locale %>"});

</script>

app/views/admin/admins/new.html.erb
<header class="header header--small">
  <%= link_to admin_admins_path, class: "btn btn--back" do %>
    <div class="arrow--left"></div>
  <% end %>

  <div class="header__content">
    <h1><%= t('admin_nav.accounts') %></h1>
    <p><%= t('admin.new_record') %></p>
  </div>
</header>

<h2 class="main__subtitle--4"><%= t('admin.profile') %></h2>
<h2 class="main__subtitle--small"><%= t('admin.resource_permissions') %></h2>

<section class="section--12 users">
  <%= render 'form' %>
</section>

app/views/admin/admins/show.html.erb
<header class="header header--small">
  <%= link_to admin_admins_path, class: "btn btn--back" do %>
    <div class="arrow--left"></div>
  <% end %>

  <div class="header__content">
    <h1><%= t('admin_nav.accounts') %></h1>
    <p><%= t('preview') %></p>
  </div>
</header>

<div class="section__wrap--4 users">
  <h2 class="main__subtitle--small"><%= t('admin.profile') %></h2>

  <section class="section section--col section--padded">
    <div class="btn__group--edit">
      <% if permission_to_edit(@admin) %>
        <%= link_to edit_admin_admin_path(@admin), class: "btn btn--edit" do %>
          <%= inline_svg "icons/pen-group-3.svg" %>
        <% end %>
      <% end %>

      <% if permission_to_delete(@admin) %>
        <%= link_to admin_admin_path(@admin), method: :delete, data: {confirm: t('delete_confirm')}, class: "btn btn--remove" do %>
          <%= inline_svg "icons/trash-simple.svg" %>
        <% end %>
      <% end %>
    </div>

    <div class="account--profile">
      <%= image_tag @admin.image_url(:thumb), class: "account__img" %>
      <h3 class="account__name"><%= @admin.full_name %></h3>
      <p class="account__email"><%= @admin.email %></p>
    </div>
  </section>

  <h2 class="main__subtitle"><%= t('permissions') %></h2>

  <section class="section section--col section--padded">
    <% if @admin.moderator? %>
      <%= render 'admin/admins/permissions_info', admin: @admin %>
    <% else %>
      <p><%= t('unlimited') %></p>
    <% end %>
  </section>
</div>

<div class="section__wrap--8">
  <h2 class="main__subtitle--small header--double"><%= t('activity') %></h2>

  <section class="section--col">
    <%= render 'admin/action_logs/action_logs_container', action_logs: @admin.action_logs %>

    <span id="js_show_more_link">
      <%#= link_to_next_page @action_logs, t('show_more'), params:{id: @admin.id}, class: 'btn', remote: true %>
    </span>
  </section>
</div>

app/views/admin/admins/show.js.erb
<% @action_logs.each do |action_log| %>
	var action_log_date = "<%= action_log.created_at.strftime('%d.%m.%Y') %>";
	var container = $(".js_date_container[data-date='"+action_log_date+"']");
	if(container.length==0){
		$(".js_action_logs").append("<div class='js_date_container' data-date='"+action_log_date+"'><h2>"+action_log_date+"</h2></div>");
	}
	container = $(".js_date_container[data-date='"+action_log_date+"']");
	container.append("<%= j render 'admin/action_logs/action_log', action_log: action_log %>");
<% end %>
$("#js_show_more_link").html('<%= link_to_next_page @action_logs, t("show_more"), params:{id: @admin.id}, class: "btn btn--tertiary", remote: true %>');
renameDates();